default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: shorty_development

test:
  <<: *default
  database: shorty_test
